# POSTGRESQL LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/rutaexpress_db
spring.datasource.username=postgres
spring.datasource.password=ELIcuci
spring.datasource.driver-class-name=org.postgresql.Driver

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database=postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# APP
spring.application.name=rutaexpress-backend
server.port=8080

# JWT
jwt.secret=rutaexpress-clave-secreta-2026-cajamarca
jwt.expiration=28800000

# PERU API (para autocompletar DNI/RUC)
peruapi.token=9fec3fc97e94d138464239bd82d8422a
peruapi.url=https://peruapi.com/